"""Phase 4: auto-remediation worker (Human-in-the-Loop).

For each critical finding we invoke MiniMax to generate an
input-sanitization patch against the target repository. The PR is **never merged
automatically** — HITL approval is mandatory per the project constitution.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Awaitable, Callable
from urllib.parse import urlparse

from openai import AsyncOpenAI

from src.config import Settings
from src.core.models import RemediationResult, RemediationTask
from src.core.truncate import truncate_text
from src.scenarios.registry import get_scenario
from src.services.github_client import GitHubClient
from src.services.remediation_engine import RemediationEngine, route_to_file_candidates

logger = logging.getLogger(__name__)


def extract_repo_full_name(repo_url: str) -> str:
    parsed = urlparse(repo_url)
    path = parsed.path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    return path


class RemediationRunner:
    """Runs a HITL remediation for one finding."""

    def __init__(self, settings: Settings, minimax: AsyncOpenAI | None = None) -> None:
        self._settings = settings
        self._github = GitHubClient(settings)
        self._engine = RemediationEngine(settings, minimax)

    @property
    def can_run_live(self) -> bool:
        return bool(
            self._settings.minimax_enabled
            and self._settings.github_token
        )

    async def run(self, task: RemediationTask) -> RemediationResult:
        if not self.can_run_live:
            return RemediationResult(
                audit_id=task.audit_id,
                repo_url=task.repo_url,
                target_url=task.target_url,
                payload=task.payload,
                aries_score=task.aries_score,
                status="unavailable",
                detail=(
                    "Remediation requires MINIMAX_API_KEY and GITHUB_TOKEN."
                ),
                technique_id=task.technique_id,
                baseline_run_id=task.baseline_run_id,
            )

        try:
            return await self._run_native(task)
        except Exception as exc:
            logger.error("Remediation failed: %s", exc, exc_info=True)
            return RemediationResult(
                audit_id=task.audit_id,
                repo_url=task.repo_url,
                target_url=task.target_url,
                payload=task.payload,
                aries_score=task.aries_score,
                status="failed",
                detail=truncate_text(str(exc), self._settings.max_error_detail_chars),
                technique_id=task.technique_id,
                baseline_run_id=task.baseline_run_id,
            )

    async def _run_native(self, task: RemediationTask) -> RemediationResult:
        repo_full_name = extract_repo_full_name(task.repo_url)

        repair_template = ""
        if task.technique_id:
            repair_template = get_scenario(task.technique_id).repair_template

        technique_tag = task.technique_id or "unknown"
        issue_title = f"Vulnerability detected: {technique_tag} (ARiES {task.aries_score}) [AUTO]"
        issue_body = (
            f"Automated vulnerability report generated by Riposte.\n\n"
            f"**Technique**: {technique_tag}\n"
            f"**ARiES Score**: {task.aries_score}\n"
            f"**Recommended controls**: {repair_template}\n"
            f"**Context**: {task.payload}\n"
        )

        evidence_hud_link = None
        if task.session_id:
            evidence_hud_link = (
                f"https://www.browserbase.com/sessions/{task.session_id}/debug"
            )

        issue_url = await self._github.create_issue(
            repo_full_name=repo_full_name,
            title=issue_title,
            body=issue_body,
            evidence_hud_link=evidence_hud_link,
        )

        return RemediationResult(
            audit_id=task.audit_id,
            repo_url=task.repo_url,
            target_url=task.target_url,
            payload=task.payload,
            aries_score=task.aries_score,
            status="issue_created",
            issue_url=issue_url,
            detail=f"Successfully opened issue: {issue_url}",
            technique_id=task.technique_id,
            baseline_run_id=task.baseline_run_id,
        )


async def patch_worker(
    remediation_queue: "asyncio.Queue",
    runner: RemediationRunner,
    on_remediation: Callable[[RemediationResult], Awaitable[None]],
    shutdown_event: asyncio.Event,
) -> None:
    while not shutdown_event.is_set():
        try:
            task: RemediationTask | None = await asyncio.wait_for(
                remediation_queue.get(), timeout=1.0
            )
        except asyncio.TimeoutError:
            continue

        if task is None:  # poison pill
            remediation_queue.task_done()
            break

        try:
            result = await runner.run(task)
            await on_remediation(result)
            logger.info("Remediation %s for audit %s", result.status, task.audit_id)
        except Exception as exc:  # pragma: no cover - defensive
            logger.error("patch_worker error: %s", exc, exc_info=True)
            await on_remediation(
                RemediationResult(
                    audit_id=task.audit_id,
                    repo_url=task.repo_url,
                    target_url=task.target_url,
                    payload=task.payload,
                    aries_score=task.aries_score,
                    status="error",
                    detail=truncate_text(str(exc), runner._settings.max_error_detail_chars),
                    technique_id=task.technique_id,
                    baseline_run_id=task.baseline_run_id,
                )
            )
        finally:
            remediation_queue.task_done()
